// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/timeline-styles/Current.tsx": () => import("../components/mockups/timeline-styles/Current.tsx"),
  "./components/mockups/timeline-styles/SansSerif.tsx": () => import("../components/mockups/timeline-styles/SansSerif.tsx"),
  "./components/mockups/timeline-styles/WarmBright.tsx": () => import("../components/mockups/timeline-styles/WarmBright.tsx")
};
